### ISSUE TITLE
permission error when setting up environment

### ISSUE THREAD

**Issue by wmelder** [netwerk-digitaal-erfgoed/ld-workbench-configuration#3]
Simply setting up the ld workbench using [this](https://github.com/netwerk-digitaal-erfgoed/ld-workbench-configuration/tree/main/amateurfilm#1---install-ld-workbench-docker) instruction set generates permission error on pipelines directory:

```
EACCES: permission denied, mkdir 'pipelines/configurations/example'
Welcome to LD Workbench version 2.8.1
file:///usr/local/lib/node_modules/@netwerk-digitaal-erfgoed/ld-workbench/build/utils/loadPipelines.js:18
            throw new Error(`No configuration files found matching pattern ${chalk.italic(`${configDirOrFile}/**/*.yml`)}`);
                  ^

Error: No configuration files found matching pattern pipelines//**/*.yml
    at loadPipelines (file:///usr/local/lib/node_modules/@netwerk-digitaal-erfgoed/ld-workbench/build/utils/loadPipelines.js:18:19)
    at file:///usr/local/lib/node_modules/@netwerk-digitaal-erfgoed/ld-workbench/build/main.js:12:23
    at file:///usr/local/lib/node_modules/@netwerk-digitaal-erfgoed/ld-workbench/build/main.js:51:3
    at ModuleJob.run (node:internal/modules/esm/module_job:274:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)

```

**Comment by EnnoMeijers** [comment]
Hi Willem, sounds like a docker file permission issue. I will try to find some time to look in to it.

**Comment by wmelder** [comment]
I noticed this [line](https://github.com/netwerk-digitaal-erfgoed/ld-workbench/blob/18ff01d1f0f4f2d4773b8faa6e8f6c56e8fafb0b/docker/Dockerfile#L8)  where user is `node`. I have no such user on my system. But I read [here](https://www.docker.com/blog/understanding-the-docker-user-instruction/) that running as `root` by default might be less secure. I am now considering to add the user 'node' and add this user to the docker group.

**Comment by EnnoMeijers** [comment]
Docker and user permissions are terrible. I don´t think this will help, the user `node` probably exists within the alpine container. Directories are created with owner `root` by Docker when the don't exists. I remember having this problem and I think I solved it by creating the directories before running the docker. In general I think the current instruction is too complex, using a smart docker-compose.yaml might solve these kind of issues. But I need some time to dive into this. @ddeboer: could you take a look at simplifying [Bob's instructions](https://github.com/netwerk-digitaal-erfgoed/ld-workbench-configuration/tree/main/amateurfilm#1---install-ld-workbench-docker) or at least solve Willem's issue?

**Comment by wmelder** [comment]
I solved this for now by allowing access to the pipelines dir for all users: `chmod a+w -R pipelines/`.
From Bob's instructions the directories are created with permission `drwxr-xr-x`. 
```
mkdir pipelines
mkdir pipelines/configurations
mkdir pipelines/data
```
Then, by running the container with the USER node, the permission denied is raised, because the write acces is denied for other users. After running chmod the permissions are `drwxrwxrwx` and the script runs ok. This is the output:
```
A boilerplate LDWorkbench has been created. You can now run a project using `npx @netwerk-digitaal-erfgoed/ld-workbench`.
Welcome to LD Workbench version 2.8.1
▶ Starting pipeline “Example Pipeline”
✔ Validating pipeline
✔ Stage “Stage 1” resulted in 612 statements in 153 iterations (took 1.6s)
✔ Stage “Stage 2” resulted in 107 statements in 1 iteration (took 765ms)
✔ Writing results to destination pipelines/data/example-pipeline.nt
✔ Your pipeline “Example Pipeline” was completed in 3.3s using 59 MB of memory
```

**Comment by EnnoMeijers** [comment]
Ah good to hear! Good luck with the next steps. I will look into creating a less complicated setup.

**Comment by ddeboer** [comment]
Yeah, @coret’s instructions are slightly weird: clone the repository _and_ run a Docker container. You only need to do one of those. I’ll experiment a bit and simplify this.

**Comment by ddeboer** [comment]
Done. @wmelder @EnnoMeijers Can you try the [new instructions](https://github.com/netwerk-digitaal-erfgoed/ld-workbench-configuration/blob/51270af9c1704f606f01c260e54d9379d02b5382/amateurfilm/README.md#1---install-ld-workbench-docker) in a fresh directory?

**Comment by wmelder** [comment]
I reset the pipelines directory and ran this step:
```
mkdir pipelines
docker run -it -v $(pwd)/pipelines:/pipelines ghcr.io/netwerk-digitaal-erfgoed/ld-workbench:latest
```
But this still fails, because of the same permission error I saw earlier.

Then I went into a new fresh directory (no repo) and ran the above.. the permission error now is: ` EACCES: permission denied, mkdir 'pipelines/data'`.
I guess the `/pipelines` folder still needs to get the right access rights. Again, `chmod a+w pipelines/` fixes the problem.

**Comment by ddeboer** [comment]
I now similarly simplified the QLever instructions.

@wmelder What OS are you on?

**Comment by wmelder** [comment]
"Ubuntu 24.04.2 LTS" (noble)

**Comment by ddeboer** [comment]
@wmelder Can you try (in a new directory, `mkdir pipelines`):

```
docker run -it -v $(pwd)/pipelines:/pipelines -u 1000:1000 ghcr.io/netwerk-digitaal-erfgoed/ld-workbench:latest
```

**Comment by wmelder** [comment]
Also errors, unfortunately: 
```
EACCES: permission denied, mkdir 'pipelines/data'
```

**Comment by wmelder** [comment]
@ddeboer 
Further down the road there's also trouble with permissions (user id 1000):
```bash
: ~/git/ld-workbench/pipelines/data$ docker run -it --rm -u 1000:1000  -v $(pwd):/data -w /data adfreiburg/qlever -c "qlever index"

Command: index

echo '{ "num-triples-per-batch": 1000000 }' > amateurfilm.settings.json
cat *.nt | IndexBuilderMain -i amateurfilm -s amateurfilm.settings.json -F ttl -f - | tee amateurfilm.index-log.txt

Writing the settings.json file failed: /usr/bin/bash: line 1: amateurfilm.settings.json: Permission denied
```

**Comment by wmelder** [comment]
I tried to run as myself: ` --user $(id -u):$(id -g)`. It does seem to work: 
```
whoami: cannot find name for user ID 1002

Command: index

echo '{ "num-triples-per-batch": 1000000 }' > amateurfilm.settings.json
cat *.nt | IndexBuilderMain -i amateurfilm -s amateurfilm.settings.json -F ttl -f - | tee amateurfilm.index-log.txt

2025-07-14 11:38:46.492 - INFO: QLever IndexBuilder, compiled on Sun Jul 13 00:18:19 UTC 2025 using git hash 8a50bb
20
...
```
Then it runs until completed.
So apart from the `whoami` showing that i am not known within the container, it was succesfull.

**Comment by wmelder** [comment]
Running the qlever container is also succesfull using the subshell commands for user:
```bash
docker run -d --user $(id -u):$(id -g) -p 8890:8890 -v $(pwd):/data -w /data adfreiburg/qlever -c "qlever start && tail -f /dev/null"
```

**Comment by wmelder** [comment]
I agree with Enno that a docker-compose file would be convenient. For now I was able to run the conversion, with some notes:

Bob's instructions are incorrect in this line:
>cp -r ../ld-workbench-configuration/amateurfilm pipelines/configurations

where the destination has to be `pipelines/configurations/amateurfilm`. 

When I change that (and set the local machine IP in the config.yml) I can run the following (again setting the user to myself):

```bash
:~/git/ld-workbench$ docker run -it --user $(id -u):$(id -g) -v $(pwd)/pipelines:/pipelines ghcr.io/netwerk-digitaal-erfgoed/ld-workbench:latest   --config pipelines/configurations/amateurfilm
Welcome to LD Workbench version 2.8.1
▶ Starting pipeline “Amateurfilm”
✔ Validating pipeline
✔ Stage “Stage 1 - Schema2EDM” resulted in 337,053 statements in 2,935 iterations (took 1m 42.8s)
✔ Stage “Stage 2 - GTAA SKOS” resulted in 9,237 statements in 4,619 iterations (took 4.6s)
✔ Writing results to destination pipelines/data/amateurfilm.nt
✔ Your pipeline “Amateurfilm” was completed in 1m 48.5s using 48 MB of memory
```

**Comment by wmelder** [comment]
Unlike before the jena commands did run without any issues:
```
$ cd ../lod-aggregator/
$ docker run -v ../ld-workbench/pipelines/data:/rdf stain/jena riot --output=rdfxml amateurfilm.nt > data/amateurfilm.xml
$ bin/convert.sh --data amateurfilm.xml --output amateurfilm.zip
Creating network "lod-aggregator_default" with the default driver
Creating lod-aggregator_convert_run ... done

Checking input parameters...

Starting conversion to XML for /opt/data/amateurfilm.xml...

Ready, results (if any) written to data/amateurfilm.zip, check data/converter.log for details...
```

**Comment by wmelder** [comment]
I noticed user is also set in the bin/convert.sh of lod-aggregator:
```sh
user=$(id -u):$(id -g)
docker-compose run --rm --user $user convert starter.sh $*
```
Might be a generic way to make sure it works for all users.

**Comment by wmelder** [comment]
> Bob's instructions are incorrect in this line:
> 
> > cp -r ../ld-workbench-configuration/amateurfilm pipelines/configurations
> 
> where the destination has to be `pipelines/configurations/amateurfilm`.

My mistake. This line is correct. The amateurfilm folder is written to configurations/
